<a href="https://colab.research.google.com/github/JoshEliell/ColabFiles/blob/main/S06_Actividad_01_Calificada_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 06 — Actividad calificable: NumPy y preparación de datos

# Actividad calificada — NumPy y preparación de datos

**Programación para Analítica Descriptiva y Predictiva**

Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---


**Nombre completo: Victor Joshua Hernandez Ramon**  
**Matrícula: 274705**  

---

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa lo visto hasta la Sesión 6: expresiones regulares (`re`), comprensión de listas, `map()`, `lambda`, y NumPy. **No uses pandas ni scikit-learn** — todavía no se han visto en el curso, y su uso no sumará puntos aunque el resultado sea correcto.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso apropiado de las herramientas indicadas en cada enunciado — una solución correcta que ignore la herramienta pedida (por ejemplo, usar un bucle `for` donde se pide `map()` o una operación vectorizada) no obtiene el puntaje completo. Comenta tu código donde el paso no sea evidente.

## Librerías

Ejecuta esta celda antes de empezar.

In [1]:
import re
import numpy as np

## Datos de partida

Una red de 4 estaciones meteorológicas registró temperatura y humedad durante 5 días. Los datos llegaron en un formato de texto crudo, como ocurre frecuentemente al recibir información de sensores o sistemas externos. Ejecuta la siguiente celda para cargar las lecturas — **no la modifiques**.

In [2]:
lecturas_crudas = [
    "EST-01 | Dia1 | Temp: 22.3C | Hum: 60%",
    "EST-01 | Dia2 | Temp: 19.8C | Hum: 64%",
    "EST-01 | Dia3 | Temp: 24.1C | Hum: 58%",
    "EST-01 | Dia4 | Temp: 26.5C | Hum: 55%",
    "EST-01 | Dia5 | Temp: 21.0C | Hum: 63%",
    "EST-02 | Dia1 | Temp: 24.0C | Hum: 70%",
    "EST-02 | Dia2 | Temp: 23.5C | Hum: 72%",
    "EST-02 | Dia3 | Temp: 27.2C | Hum: 65%",
    "EST-02 | Dia4 | Temp: 20.1C | Hum: 74%",
    "EST-02 | Dia5 | Temp: 22.8C | Hum: 69%",
    "EST-03 | Dia1 | Temp: 18.5C | Hum: 80%",
    "EST-03 | Dia2 | Temp: 19.2C | Hum: 78%",
    "EST-03 | Dia3 | Temp: 20.0C | Hum: 77%",
    "EST-03 | Dia4 | Temp: 21.5C | Hum: 75%",
    "EST-03 | Dia5 | Temp: 19.9C | Hum: 79%",
    "EST-04 | Dia1 | Temp: 27.8C | Hum: 50%",
    "EST-04 | Dia2 | Temp: 26.3C | Hum: 52%",
    "EST-04 | Dia3 | Temp: 25.9C | Hum: 53%",
    "EST-04 | Dia4 | Temp: 24.0C | Hum: 56%",
    "EST-04 | Dia5 | Temp: 28.1C | Hum: 49%",
]

print(len(lecturas_crudas), "lecturas cargadas")
print(lecturas_crudas[0])

20 lecturas cargadas
EST-01 | Dia1 | Temp: 22.3C | Hum: 60%


---

## Ejercicio 1 — Extracción con expresiones regulares (10 pts)

Usando `re` y comprensión de listas, extrae de cada cadena en `lecturas_crudas` el identificador de estación (por ejemplo `'EST-01'`) y el valor de temperatura como texto (por ejemplo `'22.3'`, sin la `C`). El resultado debe ser una lista de tuplas `(estacion, temperatura_texto)`, en el mismo orden que `lecturas_crudas`.

*Por qué importa: en la práctica, los datos casi nunca llegan ya estructurados — extraerlos de texto libre es el primer paso de cualquier pipeline de análisis.*

In [8]:
# Tu código aquí
extraidos = [
    (re.search(r"(EST-\d{2})", lectura).group(1),
     re.search(r"Temp:\s([0-9.]+)C", lectura).group(1))
    for lectura in lecturas_crudas
]
print("Primeras 10 tuplas extraidas:\n", extraidos[:10])


Primeras 10 tuplas extraidas:
 [('EST-01', '22.3'), ('EST-01', '19.8'), ('EST-01', '24.1'), ('EST-01', '26.5'), ('EST-01', '21.0'), ('EST-02', '24.0'), ('EST-02', '23.5'), ('EST-02', '27.2'), ('EST-02', '20.1'), ('EST-02', '22.8')]


---

## Ejercicio 2 — Construcción del arreglo numérico (10 pts)

A partir de las temperaturas extraídas en el Ejercicio 1 (que están en texto), usa `map()` junto con una conversión a `float` para construir un `ndarray` de tipo numérico. Verifica e imprime su `dtype`.

*Por qué importa: conectar la extracción de texto con un tipo de dato numérico utilizable es un paso que se repite constantemente al preparar datos.*

In [9]:
# Tu código aquí
temperaturas = np.array(list(map(float, [item[1] for item in extraidos])))
print("Dtype del arreglo:", temperaturas.dtype)
print("Arreglo de temperaturas:\n", temperaturas)


Dtype del arreglo: float64
Arreglo de temperaturas:
 [22.3 19.8 24.1 26.5 21.  24.  23.5 27.2 20.1 22.8 18.5 19.2 20.  21.5
 19.9 27.8 26.3 25.9 24.  28.1]


---

## Ejercicio 3 — Organización en una matriz 2D (10 pts)

Reorganiza el arreglo de temperaturas del Ejercicio 2 en una matriz de 4 filas (una por estación) × 5 columnas (una por día) usando `reshape()`. Los datos ya están ordenados por estación en `lecturas_crudas`, así que no necesitas reordenarlos manualmente. Reporta `shape`, `ndim`, `size` y `dtype` de la matriz resultante.

In [13]:
# Tu código aquí
matriz_temp = temperaturas.reshape(4, 5)

print(f"Shape: {matriz_temp.shape}")
print(f"Ndim: {matriz_temp.ndim}")
print(f"Size: {matriz_temp.size}")
print(f"Dtype: {matriz_temp.dtype}")
print("\nMatriz de temperaturas:\n", matriz_temp)


Shape: (4, 5)
Ndim: 2
Size: 20
Dtype: float64

Matriz de temperaturas:
 [[22.3 19.8 24.1 26.5 21. ]
 [24.  23.5 27.2 20.1 22.8]
 [18.5 19.2 20.  21.5 19.9]
 [27.8 26.3 25.9 24.  28.1]]


---

## Ejercicio 4 — Indexado, slicing y transposición (10 pts)

A partir de `matriz_temp`:

1. Extrae la fila completa correspondiente a `EST-03`.
2. Extrae la columna completa correspondiente al Día 4.
3. Extrae la submatriz de las primeras 2 estaciones durante los primeros 3 días.
4. Transpón la matriz con `.T` e imprime su nueva forma (`shape`). En una celda de texto (Markdown) o un comentario, explica en qué situación tendría sentido trabajar con los días como filas y las estaciones como columnas.

In [21]:
# Tu código aquí
# 1. Fila 2
fila_est03 = matriz_temp[2, :]

# 2. Columna 3
columna_dia4 = matriz_temp[:, 3]

# 3. Submatriz primeras 2 estaciones y primeros 3 dias
submatriz = matriz_temp[:2, :3]

# 4. Transposicion
matriz_transpuesta = matriz_temp.T

print("1. Fila EST-03:\n", fila_est03)
print("\n2. Columna Día 4:\n", columna_dia4)
print("\n3. Submatriz primeras 2 estaciones y primeros 3 dias:\n", submatriz)
print(f"\nShape transpuesta: {matriz_transpuesta.shape}")
print(f"\nShape transpuesta:\n {matriz_transpuesta}")

1. Fila EST-03:
 [18.5 19.2 20.  21.5 19.9]

2. Columna Día 4:
 [26.5 20.1 21.5 24. ]

3. Submatriz primeras 2 estaciones y primeros 3 dias:
 [[22.3 19.8 24.1]
 [24.  23.5 27.2]]

Shape transpuesta: (5, 4)

Shape transpuesta:
 [[22.3 24.  18.5 27.8]
 [19.8 23.5 19.2 26.3]
 [24.1 27.2 20.  25.9]
 [26.5 20.1 21.5 24. ]
 [21.  22.8 19.9 28.1]]


Originalmente filas como estaciones y dias como columnas. (Aqui en fila se agregan todos los datos de una estacion)

Trabajar con la matriz transpuesta (días como filas y estaciones como columnas) ayuda en momentos donde quieres añadir una nueva lectura diaria completa como un un nuevo registro temporal (Aqui en fila se agregan todas las temperaturas medidas de un dia), o si un modelo asume que las filas representan el tiempo y las columnas representan las variables.

---

## Ejercicio 5 — Máscaras booleanas, verificación y fancy indexing (15 pts)

1. Usa una máscara booleana sobre `matriz_temp` para identificar qué lecturas superan los 25°C.
2. Usando `any()`, verifica si **alguna** estación tuvo, en algún día, una lectura mayor a 25°C.
3. Usando `all()`, verifica si la estación `EST-04` (fila correspondiente) tuvo **todos** sus días por encima de los 24°C.
4. Usando fancy indexing, reordena las filas de `matriz_temp` según la lista de prioridad `[2, 0, 3, 1]` (es decir, primero EST-03, luego EST-01, EST-04 y EST-02).

*Por qué importa: filtrar por condición, verificar rápidamente supuestos sobre los datos, y reordenar según un criterio externo son operaciones cotidianas al priorizar qué datos revisar primero.*

In [28]:
# Tu código aquí
mascara_mayores_25 = matriz_temp > 25
alguna_mayor_25 = (matriz_temp > 25).any()
est04_todas_mayor_24 = (matriz_temp[3, :] > 24).all()
matriz_reordenada = matriz_temp[[2, 0, 3, 1], :]
print(f"1. Mascara:\n {mascara_mayores_25}")
print("\n2. ¿Alguna lectura > 25°C?:", alguna_mayor_25)
print("3. ¿EST-04 tuvo todos sus dias por encima de 24°C?:", est04_todas_mayor_24)
print("\n4. Matriz con filas reordenadas:\n", matriz_reordenada)

print("\n Matriz original:\n", matriz_temp)





1. Mascara:
 [[False False False  True False]
 [False False  True False False]
 [False False False False False]
 [ True  True  True False  True]]

2. ¿Alguna lectura > 25°C?: True
3. ¿EST-04 tuvo todos sus dias por encima de 24°C?: False

4. Matriz con filas reordenadas:
 [[18.5 19.2 20.  21.5 19.9]
 [22.3 19.8 24.1 26.5 21. ]
 [27.8 26.3 25.9 24.  28.1]
 [24.  23.5 27.2 20.1 22.8]]

 Matriz original:
 [[22.3 19.8 24.1 26.5 21. ]
 [24.  23.5 27.2 20.1 22.8]
 [18.5 19.2 20.  21.5 19.9]
 [27.8 26.3 25.9 24.  28.1]]


---

## Ejercicio 6 — Broadcasting y `np.where()` (15 pts)

Cada estación tiene un descalibre de sensor conocido, dado por este arreglo (en el mismo orden que las filas de `matriz_temp`: EST-01, EST-02, EST-03, EST-04):

```python
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])
```

1. Usa broadcasting para aplicar la corrección correspondiente a cada fila de `matriz_temp` (cada estación se ajusta con su propio valor de `descalibre`). Guarda el resultado en una variable nueva, por ejemplo `matriz_corregida`. **Pista:** si intentas sumar `matriz_temp + descalibre` directamente obtendrás un error de formas incompatibles — el broadcasting solo funciona si `descalibre` tiene la forma `(4, 1)` en lugar de `(4,)`, para que cada valor se alinee con una fila completa. Usa `reshape()` (ya lo conoces del Bloque 2) para darle esa forma antes de sumar.
2. Sobre `matriz_corregida`, usa `np.where()` para generar una matriz paralela de etiquetas de texto: `'alta'` si la lectura corregida supera los 25°C, `'normal'` en caso contrario.

In [33]:
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])

# Tu código aquí
# 1. Broadcasting usando reshape para forzar dimension (4, 1)
matriz_corregida = matriz_temp + descalibre.reshape(4, 1)

# 2. Etiquetado paralelo
etiquetas = np.where(matriz_corregida > 25, 'alta', 'normal')
print("Matriz original:\n", matriz_temp)
print("\n1. Matriz con temperaturas corregidas:\n", matriz_corregida)
print("\n2. Matriz de etiquetas (alta/normal):\n", etiquetas)


Matriz original:
 [[22.3 19.8 24.1 26.5 21. ]
 [24.  23.5 27.2 20.1 22.8]
 [18.5 19.2 20.  21.5 19.9]
 [27.8 26.3 25.9 24.  28.1]]

1. Matriz con temperaturas corregidas:
 [[21.8 19.3 23.6 26.  20.5]
 [25.2 24.7 28.4 21.3 24. ]
 [18.5 19.2 20.  21.5 19.9]
 [26.8 25.3 24.9 23.  27.1]]

2. Matriz de etiquetas (alta/normal):
 [['normal' 'normal' 'normal' 'alta' 'normal']
 ['alta' 'normal' 'alta' 'normal' 'normal']
 ['normal' 'normal' 'normal' 'normal' 'normal']
 ['alta' 'alta' 'normal' 'normal' 'alta']]


---

## Ejercicio 7 — Agregaciones por eje (15 pts)

Usando `matriz_corregida` del Ejercicio 6:

1. Calcula el promedio y la desviación estándar de temperatura **por estación** (usa el `axis` correspondiente).
2. Calcula el promedio de temperatura **por día** (usa el `axis` correspondiente).
3. Sin usar funciones no vistas en el curso (por ejemplo, sin `argmax`), determina **qué día** tuvo el promedio más alto entre estaciones. Sugerencia: obtén el valor máximo de los promedios por día con `.max()`, y compáralo con el arreglo de promedios por día usando `==` para generar una máscara booleana — la posición con `True` te dice qué día fue.

In [45]:
# Tu código aquí
# 1. Promedio y desviacion estandar por estacion
promedio_estaciones = matriz_corregida.mean(axis=1)
std_estaciones = matriz_corregida.std(axis=1)

# 2. Promedio por dia
promedio_dias = matriz_corregida.mean(axis=0)

# 3. Dia con el promedio mas alto usando ==
mascara_dia_max = (promedio_dias == promedio_dias.max())
indice_dia = list(mascara_dia_max).index(True)
dia_maximo = indice_dia + 1

print("1. Promedio de temp. por estación:\n", promedio_estaciones)
print("1. Desviación estándar por estación:\n", std_estaciones)
print("\n2. Promedio de temp. por día:\n", promedio_dias)
print(f"\n3. Máscara del día máximo: {mascara_dia_max}")
print(f"El dia con el promedio más alto fue el Dia {dia_maximo}")

1. Promedio de temp. por estación:
 [22.24 24.72 19.82 25.42]
1. Desviación estándar por estación:
 [2.36016949 2.27982455 0.99879928 1.4743134 ]

2. Promedio de temp. por día:
 [23.075 22.125 24.225 22.95  22.875]

3. Máscara del día máximo: [False False  True False False]
El dia con el promedio más alto fue el Dia 3


---

## Ejercicio 8 — Síntesis: resumen por estación (15 pts)

Usando `map()` y/o comprensión de listas, genera una lista de cadenas de resumen, una por estación, que combine:

- El identificador de estación extraído en el Ejercicio 1.
- El promedio de temperatura corregida de esa estación (Ejercicio 7), formateado a un decimal.
- Su clasificación predominante (`'alta'` o `'normal'`) — usa `np.unique()` sobre las etiquetas de esa estación (del Ejercicio 6) para encontrar cuál aparece con mayor frecuencia entre las dos.

Formato esperado por cadena: `"EST-01: 23.4°C promedio — clasificación predominante: normal"`

Finalmente, ordena la lista de resúmenes de mayor a menor promedio de temperatura usando `sorted()` con `key` y `lambda` (como en la Sesión 4/5), e imprime el resultado ordenado.

In [49]:
# Tu código aquí
# Extraer ids manteniendo el orden sin duplicados
estaciones_ids = []
[estaciones_ids.append(e[0]) for e in extraidos if e[0] not in estaciones_ids]

def obtener_predominante(fila_etiquetas):
    valores, conteos = np.unique(fila_etiquetas, return_counts=True)
    return valores[list(conteos).index(max(conteos))]

# Construcción de la cadena con lista
resumenes = [
    f"{estaciones_ids[i]}: {promedio_estaciones[i]:.1f}°C promedio — clasificación predominante: {obtener_predominante(etiquetas[i])}"
    for i in range(4)
]

# Ordenamiento con sorted() y lambda para el float
resumenes_ordenados = sorted(
    resumenes,
    key=lambda cadena: float(re.search(r"([0-9.]+)", cadena).group(1)),
    reverse=True
)

for resumen in resumenes_ordenados:
    print(resumen)

EST-04: 25.4°C promedio — clasificación predominante: alta
EST-03: 19.8°C promedio — clasificación predominante: normal
EST-02: 24.7°C promedio — clasificación predominante: normal
EST-01: 22.2°C promedio — clasificación predominante: normal


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.
- Revisa que tu nombre y número de control estén en la primera celda.