<a href="https://colab.research.google.com/github/JoshEliell/ColabFiles/blob/main/S06_Actividad_NumPy_274705_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**

Maestría en Inteligencia Artificial y Analítica de Datos — UACJ
---


**Nombre completo: Victor Joshua Hernandez Ramon**  
**Matrícula: 274705**  

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [31]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [32]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [33]:
# Tu código aquí
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print(f"Norma de A: {norma_A:.4f}")
print(f"Norma de B: {norma_B:.4f}")
print(f"Norma de C: {norma_C:.4f}")

Norma de A: 7.4492
Norma de B: 6.7772
Norma de C: 5.2383


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [34]:
# Tu código aquí
# 1. Producto punto usando @
punto_AB = producto_A @ producto_B
punto_AC = producto_A @ producto_C

# 2. Cálculo del ángulo (en grados)
# Primero calculamos el coseno del ángulo, luego arccos y finalmente pasamos a grados
cos_theta_AB = punto_AB / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
angulo_AB = np.degrees(np.arccos(cos_theta_AB))

cos_theta_AC = punto_AC / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))
angulo_AC = np.degrees(np.arccos(cos_theta_AC))

print(f"Producto punto A y B: {punto_AB:.4f}, Ángulo: {angulo_AB:.2f}°")
print(f"Producto punto A y C: {punto_AC:.4f}, Ángulo: {angulo_AC:.2f}°")

Producto punto A y B: 50.4600, Ángulo: 1.77°
Producto punto A y C: 26.5000, Ángulo: 47.23°


El producto_B es más similar al producto_A. El ángulo es el indicador, porque mide geometricamente la diferencia de dirección entre ambos vectores, un ángulo más pequeño significa que los productos comparten una proporcion mas parecida.

---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [35]:
# Tu código aquí
A_unitario = producto_A / np.linalg.norm(producto_A)
B_unitario = producto_B / np.linalg.norm(producto_B)
C_unitario = producto_C / np.linalg.norm(producto_C)

print("Norma A normalizado:", np.linalg.norm(A_unitario))
print("Norma B normalizado:", np.linalg.norm(B_unitario))
print("Norma C normalizado:", np.linalg.norm(C_unitario))

Norma A normalizado: 1.0
Norma B normalizado: 1.0
Norma C normalizado: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [36]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [37]:
# Tu código aquí
# 1. Comparación
print("Multiplicación elemento a elemento:\n", M * P)
print("\nMultiplicación matricial (M @ P):\n", M @ P)

# 2. Compatibilidad de formas (P @ M)
print("\nMultiplicación matricial (P @ M):\n", P @ M)

Multiplicación elemento a elemento:
 [[3. 0.]
 [0. 6.]]

Multiplicación matricial (M @ P):
 [[3.  2. ]
 [1.5 6. ]]

Multiplicación matricial (P @ M):
 [[3.  1.5]
 [2.  6. ]]


Los resultados de M @ P y P @ M son diferentes. Esto demuestra que la multiplicación matricial no es conmutativa. El orden de los factores sí altera el producto en el álgebra lineal clásica.

---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [38]:
# Tu código aquí
# 1. Determinante
det_M = np.linalg.det(M)
print("Determinante de M:", det_M)

# 2. Inversa
M_inv = np.linalg.inv(M)
print("\nInversa de M:\n", M_inv)

# 3. Verificación
print("\nVerificación (M @ M_inv):\n", M @ M_inv)

Determinante de M: 5.000000000000001

Inversa de M:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

Verificación (M @ M_inv):
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


1. Como es distinto de 0, tiene inversa.
3. Si dio aproximadamente la matriz identidad

---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [39]:
b = np.array([180, 300])

# Tu código aquí
# 1. Resolución
x = np.linalg.solve(M, b)
print("Unidades necesarias de cada insumo (x):", x)

# 2. Verificación
print("\nVerificando (M @ x):", M @ x) # El resultado debe ser [180. 300.]

Unidades necesarias de cada insumo (x): [48. 84.]

Verificando (M @ x): [180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [40]:
# Tu código aquí
# 1. Distancia Euclidiana
distancia_AB = np.linalg.norm(producto_A - producto_B)
distancia_AC = np.linalg.norm(producto_A - producto_C)
print("Distancia euclidiana A-B:", distancia_AB)
print("Distancia euclidiana A-C:", distancia_AC)

# 2. Similitud Coseno
similitud_AB = (producto_A @ producto_B) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
similitud_AC = (producto_A @ producto_C) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))
print("\nSimilitud coseno A-B:", similitud_AB)
print("Similitud coseno A-C:", similitud_AC)

Distancia euclidiana A-B: 0.7071067811865476
Distancia euclidiana A-C: 5.470831746635972

Similitud coseno A-B: 0.9995203969214979
Similitud coseno A-C: 0.6791199021706347


3. El producto B es más parecido al producto A.

 Ambas métricas coinciden: el par A-B tiene una menor distancia euclidiana y una mayor similitud coseno (más cercana a 1) en comparación con el par A-C."

---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.